// Generated by build.py!
//
// Contains unique build info (useful for tracking the version people are using!)
namespace NEP.DOOMLAB
{
    static partial class BuildInfo
    {
		public const int Epoch = 1697578723;
		public const string GitCommit = "13b546a1524cf7e5e534aea924b166e25f48b5a3";
    }
}