// Generated by build.py!
//
// Contains unique build info (useful for tracking the version people are using!)
namespace NEP.DOOMLAB
{
    static partial class BuildInfo
    {
		public const int Epoch = 1696875461;
		public const string GitCommit = "bb271d91b8e425fda10d7f85b32db17e8b845194";
    }
}