// Generated by build.py!
//
// Contains unique build info (useful for tracking the version people are using!)
namespace NEP.DOOMLAB
{
    static partial class BuildInfo
    {
		public const int Epoch = 1693832241;
		public const string GitCommit = "06fa703ccaa52fecfb136e95dedb362ea3a3f15e";
    }
}